import javax.swing.JOptionPane;

public class Branch extends javax.swing.JFrame {

    public Branch() {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {
        // Initialize components (auto-generated by GUI builder)
        // Add your UI components here
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Add branch logic
        int BranchNo = Integer.parseInt(BranchB.getText());
        String Address = AddressB.getText();
        String Country = CountryB.getText();
        String Phone = PhoneB.getText();
        String Email = EmailB.getText();

        Branchclass BR = new Branchclass();
        BR.setBranchNo(BranchNo);
        BR.setAddress(Address);
        BR.setCountry(Country);
        BR.setPhoneNo(Phone);
        BR.setEmail(Email);

        if (BR.AddObjectToFile()) {
            JOptionPane.showMessageDialog(null, "Branch added successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add branch.");
        }
    }

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {
        // Go back to the main menu
        this.dispose(); // Close the current window
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Branch().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JTextField AddressB;
    private javax.swing.JTextField BranchB;
    private javax.swing.JTextField CountryB;
    private javax.swing.JTextField EmailB;
    private javax.swing.JTextField PhoneB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonback;
}