import javax.swing.JOptionPane;

public class Doctor extends javax.swing.JFrame {

    public Doctor() {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {
        // Initialize components (auto-generated by GUI builder)
        // Add your UI components here
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Add doctor logic
        int ID = Integer.parseInt(DoctorID.getText());
        String First = FirstNameD.getText();
        String Last = LastNameD.getText();
        int Age = Integer.parseInt(AgeD.getText());
        String Specialization = SpecializationD.getText();
        int Salary = Integer.parseInt(SalaryD.getText());
        String Email = EmailD.getText();
        String Phone = PhoneD.getText();
        String Address = AddressD.getText();
        String Martial = MartialD.getSelectedItem().toString();
        String Gender = GenderD.getSelectedItem().toString();
        String Blood = BloodD.getSelectedItem().toString();
        int Month = Integer.parseInt(MonthD.getSelectedItem().toString());
        int Day = Integer.parseInt(DayD.getSelectedItem().toString());
        int Year = Integer.parseInt(YearD.getSelectedItem().toString());

        Doctorclaas DC = new Doctorclaas();
        DC.setDID(ID);
        DC.setFirstname(First);
        DC.setLastname(Last);
        DC.setAge(Age);
        DC.setSpecialization(Specialization);
        DC.setSalary(Salary);
        DC.setEmail(Email);
        DC.setPhone(Phone);
        DC.setAddress(Address);
        DC.setMartial(Martial);
        DC.setGender(Gender);
        DC.setBlood(Blood);
        DC.setMonth(Month);
        DC.setDay(Day);
        DC.setYear(Year);

        if (DC.AddObjectToFile()) {
            JOptionPane.showMessageDialog(null, "Doctor added successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add doctor.");
        }
    }

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {
        // Go back to the main menu
        this.dispose(); // Close the current window
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JTextField AddressD;
    private javax.swing.JTextField AgeD;
    private javax.swing.JComboBox<String> BloodD;
    private javax.swing.JComboBox<String> DayD;
    private javax.swing.JTextField DoctorID;
    private javax.swing.JTextField EmailD;
    private javax.swing.JTextField FirstNameD;
    private javax.swing.JComboBox<String> GenderD;
    private javax.swing.JTextField LastNameD;
    private javax.swing.JComboBox<String> MartialD;
    private javax.swing.JComboBox<String> MonthD;
    private javax.swing.JTextField PhoneD;
    private javax.swing.JTextField SalaryD;
    private javax.swing.JTextField SpecializationD;
    private javax.swing.JComboBox<String> YearD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonback;
}