import javax.swing.JOptionPane;

public class Nurses extends javax.swing.JFrame {

    public Nurses() {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {
        // Initialize components (auto-generated by GUI builder)
        // Add your UI components here
    }

    private void jButtonAddressNActionPerformed(java.awt.event.ActionEvent evt) {
        // Add nurse logic
        int ID = Integer.parseInt(NursesID.getText());
        String First = FirstNameN.getText();
        String Last = LastNameN.getText();
        int Age = Integer.parseInt(AgeN.getText());
        String Martial = MatrialN.getSelectedItem().toString();
        int Month = Integer.parseInt(MonthN.getSelectedItem().toString());
        int Day = Integer.parseInt(Dayn.getSelectedItem().toString());
        int Year = Integer.parseInt(YearN.getSelectedItem().toString());
        String Blood = BloodgroupN.getSelectedItem().toString();
        String Gender = GenderN.getSelectedItem().toString();
        int Salary = Integer.parseInt(SalaryN.getText());
        String Email = EmailN.getText();
        String Phone = PhoneN.getText();
        String Address = AddressN.getText();

        Nursesclass NC = new Nursesclass();
        NC.setNID(ID);
        NC.setFirstname(First);
        NC.setLastname(Last);
        NC.setAge(Age);
        NC.setMartial(Martial);
        NC.setMonth(Month);
        NC.setDay(Day);
        NC.setYear(Year);
        NC.setBlood(Blood);
        NC.setGender(Gender);
        NC.setSalary(Salary);
        NC.setEmail(Email);
        NC.setPhone(Phone);
        NC.setAddress(Address);

        if (NC.AddObjectToFile()) {
            JOptionPane.showMessageDialog(null, "Nurse added successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add nurse.");
        }
    }

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {
        // Go back to the main menu
        this.dispose(); // Close the current window
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nurses().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JTextField AddressN;
    private javax.swing.JTextField AgeN;
    private javax.swing.JComboBox<String> BloodgroupN;
    private javax.swing.JComboBox<String> Dayn;
    private javax.swing.JTextField EmailN;
    private javax.swing.JTextField FirstNameN;
    private javax.swing.JComboBox<String> GenderN;
    private javax.swing.JTextField LastNameN;
    private javax.swing.JComboBox<String> MatrialN;
    private javax.swing.JComboBox<String> MonthN;
    private javax.swing.JTextField NursesID;
    private javax.swing.JTextField PhoneN;
    private javax.swing.JTextField SalaryN;
    private javax.swing.JComboBox<String> YearN;
    private javax.swing.JButton jButtonAddressN;
    private javax.swing.JButton jButtonback;
}